{% set name = "lb-telemetry" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-telemetry-{{ version }}.tar.gz
  sha256: 05d5af5f1462ba5aaf808ac97970416a52309a794fcf906c6f63d2afa42b77af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6
    - lbplatformutils
    - logzero
    - requests

test:
  imports:
    - lb_telemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb/lb-telemetry
  summary: A utility for logging telemetry data from LHCb packages to MONIT
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - CameronMcClymont
